### ISSUE TITLE
Get rid of uses of ArrayList. Use List<T> instead

### ISSUE THREAD

**Issue by camiblanch** [jtcotton63/cs312-project05-clean-refactor#1]
I've seen people advising against using ArrayList all over stackoverflow while working on this project. [http://stackoverflow.com/questions/2309694/arraylist-vs-list-in-c-sharp](http://stackoverflow.com/questions/2309694/arraylist-vs-list-in-c-sharp)

**Comment by teuber789** [comment]
I totally agree. I'll have to go through and replace the ArrayList references with List.

**Comment by camiblanch** [comment]
Great! I can help after the semester's over. I'm too swamped right now

**Comment by teuber789** [comment]
Done c2c8f704c3d10e26bdb9ffc871bba57d5be5393a. @camiblanch if you want, feel free to review.
